// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ExbrppdwwHtaGqYICRQViY7MybUxzyg',
    appId: '1:479920566784:web:4368ab06eddace341e1ee5',
    messagingSenderId: '479920566784',
    projectId: 'lmss-a5b52',
    authDomain: 'lmss-a5b52.firebaseapp.com',
    storageBucket: 'lmss-a5b52.firebasestorage.app',
    measurementId: 'G-QPDDZ0C4R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_UFldit5DQ__GWnDYM_m0azGuBXeUxs',
    appId: '1:479920566784:android:457abc16956f8fa11e1ee5',
    messagingSenderId: '479920566784',
    projectId: 'lmss-a5b52',
    storageBucket: 'lmss-a5b52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZmLKwuS79Do5JmGsQkxIKxwyKmwta9w',
    appId: '1:479920566784:ios:20d90d45c8263ee71e1ee5',
    messagingSenderId: '479920566784',
    projectId: 'lmss-a5b52',
    storageBucket: 'lmss-a5b52.firebasestorage.app',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZmLKwuS79Do5JmGsQkxIKxwyKmwta9w',
    appId: '1:479920566784:ios:20d90d45c8263ee71e1ee5',
    messagingSenderId: '479920566784',
    projectId: 'lmss-a5b52',
    storageBucket: 'lmss-a5b52.firebasestorage.app',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ExbrppdwwHtaGqYICRQViY7MybUxzyg',
    appId: '1:479920566784:web:d4866bb39057fd061e1ee5',
    messagingSenderId: '479920566784',
    projectId: 'lmss-a5b52',
    authDomain: 'lmss-a5b52.firebaseapp.com',
    storageBucket: 'lmss-a5b52.firebasestorage.app',
    measurementId: 'G-3G07T0H4DY',
  );
}
